#!/bin/bash

create_object() {
    local instance_name=$1
    local OBJECT_FILE="$2"

    eval "$(sed "s/\${obj}_/${instance_name}_/g" "$OBJECT_FILE")"

    local init_function=${instance_name}_init
    if command -v $init_function &>/dev/null; then
        shift 2
        if ! $init_function $@; then
            echo "Initialization failed: $init_function" >&2
        fi
    fi
}

