#!/bin/bash

create_object() {
    local instance_name=$1
    local object="$2"

    echo "${object//"\${obj}_"/${instance_name}_}"

    local init_function=${instance_name}_init
    if command -v $init_function &>/dev/null; then
        shift 2
        if ! $init_function $@; then
            echo "Initialization failed: $init_function" >&2
            exit 1
        fi
    fi
}

